### ISSUE TITLE
Search venue by location not working

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#35]
Tap on coffee, tap on venue search. Type in Denver so I can find a coffee shop in Denver to buy Josh a drink. Does not do anything, continues to show the default list of venues.

**Comment by volkzayaz** [comment]
@kostya-p-dev, issue is reproducible on current build.

    http://104.131.69.192/api/venues/

    cityQuery:NewYork
    favorites:false

and 

    http://104.131.69.192/api/venues/

    cityQuery:Denver
    favorites:false

return identical sets of Venues.

If it helps, Forsquare expect **only one** of two be present in query. Either `ll` param **or** `near`

**Comment by kostya-p-dev** [comment]
Done

**Comment by volkzayaz** [comment]
Venues do not contain `category` info.

Take a look at `http://104.131.69.192/api/venues/?favorites=false&category=3`

     {
      "data": [
        {
          "pk": "4a6bdc59f964a52020d01fe3",
          "name": "Gjelina",
          "address": "1429 Abbot Kinney Blvd",
          "latitude": 33.990504139684,
          "longitude": -118.46497803926,
          "category": 3
        },
     .....

Now requesting details of the venue:
`http://104.131.69.192/api/venue/4a6bdc59f964a52020d01fe3`

     {
       "data": {
         "id": "4a6bdc59f964a52020d01fe3",
         "price": 3,
         "rating": 9.4,
         "name": "Gjelina",
         "address": "1429 Abbot Kinney Blvd",
         "latitude": 33.990504139684,
         "longitude": -118.46497803926,
         "category": null
       },

 **"category": null**. @kostya-p-dev, please take a look

**Comment by kostya-p-dev** [comment]
Done

**Comment by jmatheson** [comment]
This seems to show different venues now, but no matter what city i type in it returns the same set of venes.

**Comment by volkzayaz** [comment]
Typo in ios request serialization. Issue is fixed in 0.0.11. @jmatheson, please verify in 0.0.11 build when it's available.

**Comment by jmatheson** [comment]
This is still not working. I type in san francisco and i see venues in australia.

**Comment by jidulberger** [comment]
I'm getting a lot of 500 errors when attempting to enter a city, for example when typing "San Francisco" I get an error when I can to "San Fra..."

**Comment by jmatheson** [comment]
This still does not work properly.
I type in Denver and press search and nothing happens.
Also this feature worked previously as an auto search, so as I was typing in a name of a venue or city it would automatically filter the and show the results in real time after 3 or 4 letters.
Please see old code for how it worked.

**Comment by jidulberger** [comment]
This also appears to be working as expected.
